import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SmoothScroll from "../components/SmoothScroll";
import TargetCursor from "../components/TargetCursor";
import ClickSpark from "../components/ClickSpark";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <TargetCursor
          targetSelector="a,button,footer a, footer button, header a, header button, header .header-logo"
          spinDuration={2.5}
          hideDefaultCursor={true}
          cursorColor="rgba(255, 255, 255, 0.85)"
          cursorColorOnTarget="#9a0002"
        />
        <SmoothScroll />
        <ClickSpark
          sparkColor="#9a0002"
          sparkSize={12}
          sparkRadius={25}
          sparkCount={15}
          duration={500}
        >
          {children}
        </ClickSpark>
      </body>
    </html>
  );
}
